5 dev login
Avocado-Community/api.avocadogrowth pull request #13
Opened 2024-04-17 09:01 UTC by Moumouuu

# Description

Allow user to login

## Related Issue(s)

For this issue : https://github.com/Avocado-Community/api.avocadogrowth/issues/5

## Type of change

Please check options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation enhancement

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-04-17 09:03 UTC, Moumouuu commented
I reversed my two commit, "write test" is for "allow user" and vice versa

2024-04-18 15:55 UTC, quentinhaenn requested changes

2024-04-18 15:55 UTC, quentinhaenn commented on tests/unit/session/create.spec.ts
> +          message: 'The password must be at least 8 characters long',
Not sure if the error message has to be "not long enough". I prefer "wrong password", no ?

2024-04-19 10:52 UTC, Moumouuu commented on tests/unit/session/create.spec.ts
> +          message: 'The password must be at least 8 characters long',
No because i test if password have min 8 characters & not if the credentials are correct, on the other this test is missing

2024-04-19 15:09 UTC, quentinhaenn approved these changes

2024-04-19 15:09 UTC, merged